/** Declaration file generated by dts-gen */

declare function GoogleTranslate(apiKey: any, newConcurrentLimit?: any): Translator;

declare namespace GoogleTranslate {
    const prototype: {
    };
}

export interface Translator {
    translate(text: string, sourceLang: string, targetLang: string, callback: (err: Error, translation: { translatedText: string, originalText: string }) => void): void;
}

export default GoogleTranslate;